GatewayLang = {};   
//任务调度
GatewayLang.Schedule = {
	"running":"运行中的任务",
	"completed":"已完成任务",
	"fail":"异常任务",
	"task_name":"任务名称",
	"start_run_time":"开始运行时间",
	"type":"任务类型",
	"desc":"任务描述",
	"start_time":"开始时间",
	"end_time":"结束时间",
	"status":"状态",
	"Operating_status":"步骤",
	"error_message":"错误信息",
	"task_desc":"任务描述",
	"last_start_time":"上次开始时间",
	"last_end_time":"上次结束时间",
	"Automated_tasks":"自动任务",
	"Manual_tasks":"手动任务",
	"Running_time":"运行时间",
	"Partially_completed":"部分完成",
	"Information":"信息",
	"Timing_tasks":"定时任务",
	"Adapter_task":"适配器任务",
	"Custom_task":"自定义任务",
	"Time":"时间",
	"Task_details":"任务明细",
	"Stopping":"停止中",
	"Confirmation_suspended_task":"确认暂停任务吗",
	"Confirm_to_the_task":"确认开始任务吗",
	"Confirm_execution_of_manual_task":"确认执行手动任务吗",
	"Confirm_delete_tasks":"确认删除任务吗",
	"Confirm_resume_tasks":"确认恢复任务吗",
	"Confirm_stop_task":"确认停止任务吗",
	"New_adapter_task":"新适配器任务",
	"Add_a_custom_task":"新增自定义任务",
	"View_data":"查看抽取数据",
	"Download_file":"下载文件",
	"Error_executing":"执行出错，任务已终止",
	"Manual_tasks_completed":"手动任务执行完毕",
	"End":"结束",
	"The_task_script_is_invalid":"任务脚本无效",
	"Time_expression_illegal":"非法的时间表达式",
	"Task_script":"任务脚本",
	"Script_Parameters":"脚本参数",
	"Format":"格式",
	"Each_parameter_is_a_line":"每个参数为一行",
	"Trigger_mode":"触发模式",
	"Manual_trigger":"手动触发",
	"Advanced":"高级",
	"Fixed_time_trigger":"固定时刻触发",
	"Calendar_cycle_trigger":"日历周期触发",
	"Expression":"表达式",
	"Time_interval":"间隔时间(秒)",//Time_interval_(seconds)
	"Execution_times":"执行次数",
	"unlimited":"如果为0表示不限次数，直到结束时间为止",//If 0 is unlimited, until the end of time
	"Trigger_time":"触发时间",
	"Hour":"时",
	"Minute":"分",
	"Second":"秒",
	"Month":"月",
	"Day":"日",
	"Week":"周几",
	"Year":"年",
	"Days_of_the_month":"月中的天",
	"Day_of_the_week":"周中的天",
	"Circulation_pattern":"循环模式",
	"Daily":"每日",
	"Weekly":"每周",
	"Monthly":"每月",
	"Every_year":"每年",
	"Cycle_value":"循环值",
	"The_first_X_days_per_month":"每月第X天",
	"Inform_the_phone":"告警手机",
	"Information_notification_email":"告警Email",
	"Task_parameters":"任务参数",
	"Select_the_adapter":"选择适配器",
	"task_run_succ":"任务已执行",
	"task_run_fail":"任务执行失败",
	"autosend":"是否自动发送",
	"taskId":"任务ID",
	"Effective_time" : "有效时间",
    "Failure_time" : "失效时间",
    "Host":"运行实例",
    "Data_Adapter_Id":"数据适配器",
    "job_name":"作业名称",
    "New_adapter_job":"新增适配器作业",
    "Add_a_custom_job":"新增自定义作业",
    "job_type":"作业类型",
    "Adapter_job":"适配器作业",
    "Custom_job":"自定义作业",
    "job_desc":"作业描述",
    "job_parameters":"作业参数",
    "job_script":"作业脚本"
}   
//公用
GatewayLang.Public = {
	"Save" : "保存",
	"Add" : "新增",
	"Delete" : "删除",
	"Edit" : "编辑",
	"Cancel" : "取消",
	"Refresh" : "刷新",
	"Action":"操作",
	"Operate_success":"操作成功",
	"Operate_fail":"操作失败",
	"Close" : "关闭",
	"Ensure" : "确定",
	"Delete_success" : "删除成功",
	"Delete_fail" : "删除失败",
	"Save_success" : "保存成功",
	"Save_fail" : "保存失败",
	"Please_select_row" : "请选择行",
	"Confirm_delete_information" : "是否删除信息",
	"Confirm_save_information":"是否保存信息",
	"True" : "是",
	"False" : "否",
	"Search" : "查询",
	"UserName" : "用户名",
	"Password" : "密码",
	"Email":"邮件",
	"There_no_data" : "当前没有数据。",
	"Upload_data" : "上传数据",
	"Upload" : "上传",
	"Download_template" : "下载模板",
	"Send_data":"确认",
	"Run_successfully" : "运行成功",
	"Failed_to_run":"运行失败",
	"Pause":"停用",
	"View_details":"查看明细",
	"Stop":"停止",
	"Resume":"启用",
	"Manual_execution":"手动执行",
	"desc":"描述",
	"download":"下载",
	"This_value_can_not_be_empty":"该值不可为空",//该值不可为空
	"Unique_key":"唯一主键",
	"Key":"主键",
	"File_name":"文件名",
	"Select_text":"选择...",
	"Upload_success":"上传成功",
	"Upload_fail":"上传失败",
	"System_confirm_dialog":"系统确认框",
	"System_confirm":"是否系统确认",
	"Sunday":"星期日",
	"Monday":"星期一",
	"Tuesday":"星期二",
	"Wednesday":"星期三",
	"Thursday":"星期四",
	"Friday":"星期五",
	"Saturday":"星期六",
	"Configure":"配置",
	"Original_password":"原密码",
	"New_password":"新密码",
	"Confirm_password":"确认密码",
	"status":"状态",
	"Total_of":"共",
	"Page":"页",
	"hidden":"隐藏",
	"show_menu":"展开菜单",
	"hidden_menu":"隐藏菜单",
	"Prompted":"系统提示",
	"Today":"本日",
	"ThisWeek":"本周",
	"ThisMonth":"本月",
	"Import":"导入",
	"detail":"详情",
	"titleinfo":"头信息",
	"detailinfo":"行信息", 
	"Print_download":"打印订单",
	"post_code":"邮编",
	"Data_is_not_checked":"未勾选数据",
	"define":"定义",
	"memo":"备注",
	"managerconfig":"配置",
	"business_type_purchase_order":"采购订单",
	"business_type_invoice":"发票",
	"business_type_sales_order":"销售订单",
	"has":"有",
	"has_not":"没有",
	"version":"版本",
	"confirmproce":"确认处理此数据?",
	"Whether_required":"是否必填",
	"remoteRestar":"重启",
	"confirmRestart":"确认远程重启吗?",
	"remoteCommand":"远程重启命令已提交!",
	"Category":"分类",
	"File_path_error":"文件路径错误",
	"version":"版本"
}

//适配器
GatewayLang.Adapter = {
	"Adapter_list":"适配器列表",
	"Code":"编码",
	"Trade_name":"厂商名称",
	"ProductLine":"产品系列",
	"Adapter_name":"适配器名称",
	"DataBase_ip_address":"数据库IP地址",
	"Adapter_param_configure":"适配器参数配置",
	"Work_catalog":"工作目录",
	"Data_transform_script":"数据转换脚本",
	"Data_validate_script":"数据校验脚本",
	"Param_configure_hint":"如:key=value每一行为一组键值对",
	//////////
	"adapter_setting_step1":"基本设置",
	"adapter_setting_step2":"参数设置",
	"lable_business_type":"业务类型",
	"lable_adaptor_type":"适配器类型",
	"lable_code":"编码",
	"lable_firm_name":"厂商名称",
	"lable_product_series":"产品系列",
	"lable_adaptor_name":"适配器名称",
	"lable_desc":"适配器描述",
	"hasCSVheader":"是否有CSV头",
	"field_mapping":"字段映射",
	"edi_field_name":"EDI字段名",
	"csv_field_name":"csv字段名",
	"excel_field_column":"excel列号",
	"field_desc":"字段描述",
	"DataBase_driver" : "数据库驱动",
	"DataBase_user_name" : "数据库用户",
	"DataBase_password" : "数据库密码",
	"DataBase_pre_sql":"预处理语句",
	"DataBase_process_sql":"处理语句",
	"DataBase_post_sql":"后处理语句",
	"excel_begin_row":"开始行",
	"excel_end_row":"结束行",
	"excel_sheet":"工作单（Sheet）",
	"adaptor_db":"数据库适配器",
	"adaptor_csv":"CSV适配器",
	"adaptor_excel":"Excel适配器",
	"extractDate":"数据抽取频率",
	"length":"长度",
	"type":"类型",
	"columname":"数据库字段名",
	"Business_type_field":"业务类型字段",
	"javacode":"Java代码",
	"selecttemp":"请选择模板",
	"new_adapter":"新增适配器",
	"Adapter_template":"适配器模板",
	"Dedicated_adapter":"专用适配器",
	"Universal_adapter":"通用适配器",
	"The_main_business_type":"该主业类型",
	"Didnotgettofield":"没有获取到字段!",
	"remoteupgrade":"远程更新操作已提交!",
	"comfirmcommit":"确认提交更新?",
	"commitremote":"提交远程更新",
	"notmodify":"未修改数据,无需提交!",
	"transformerscript":"Transformer 脚本",
	"notdelete":"已在任务中已配置，不能删除",
	"Extraction_frequency":"抽取天数(默认30天)"
}

//日志
GatewayLang.Log = {
	"Transaction_log":"交易日志",
	"Non_repudiation_log":"非抵赖日志",
	"Transaction_protocol":"交易协议",
	"Transaction_type":"交易类型",
	"Trading_partners":"交易伙伴",
	"Direction":"方向",
	"Description":"描述",
	"Time":"时间",
	"Transaction_codes":"交易编码",
	"Start_date":"开始日期",
	"End_date":"结束日期",
	"Upstream":"上行",
	"Downstream":"下行",
	"Protocol":"协议",
	"Category":"类别",
	"TransactionID":"交易ID",
	"status":"状态",
	"date":"日期",
	"The_file_does_not_exist":"文件不存在",
	"Detail_information":"明细信息",
	"Business_type":"业务类型"
}